-- ════════════════════════════════════════════════════════════════════════════
-- DÉPLACÉ — ne rien définir ici.
--
-- Le pont Auth (trigger `on_auth_user_created`), le rôle initial dans
-- `app_metadata`, l'Access Token Hook (`custom_access_token_hook`) et la RLS
-- sont désormais CENTRALISÉS dans le fichier canonique :
--
--     prisma/manual/0001_extensions_rls_auth.sql   (§C pont Auth, §D RLS, §E hook)
--
-- Pourquoi ce déplacement : cette version historique définissait le même trigger
-- avec des identifiants de table ERRONÉS (`public.users` minuscule au lieu de la
-- table Prisma `public."User"`), et le hook avec les rattachements commentés. Avoir
-- deux définitions divergentes de `handle_new_user()` = drift garanti (la dernière
-- appliquée écrase l'autre). Source unique de vérité = le fichier canonique ci-dessus,
-- référencé par l'en-tête de prisma/schema.prisma et le runbook prisma/manual/README.md.
--
-- Runbook d'application : prisma/manual/README.md.
-- ════════════════════════════════════════════════════════════════════════════
